TARGET = XTAG2
APP_NAME =
XCC_FLAGS = -O2 -fllvm
USED_MODULES = module_jtag_master module_xcore_debug

# Use the main Makefile from module_xmos_common
include ../../xcommon/module_xcommon/build/Makefile.common
