TARGET = XK-1A
APP_NAME =
XCC_FLAGS = -O2 
USED_MODULES = module_jtag_master module_xcore_debug module_xs1_su_debug module_jtag_otp_access

# Use the main Makefile from module_xmos_common
XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
